name: Firewood Node.js

on:
	push:
		branches: [ main ]

jobs:
	build:
		runs-on: windows-latest
	steps:
		- name: Setup Node.js environment
  		uses: actions/setup-node@v3.2.0
		with:
			node-version: latest
		- run: npm install